name: Deploy to Kintone
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install @kintone/customize-uploader
        run: npm install -g @kintone/customize-uploader

      - name: Build file
        run: npm install && npm run build
      
      - name: Deploy to Kintone
        run: |
          kintone-customize-uploader --base-url ${{ secrets.KINTONE_DOMAIN }} --username ${{ secrets.KINTONE_USER_NAME }} --password ${{ secrets.KINTONE_USER_PASSWORD }} manifest.prod.json
